<a href="https://colab.research.google.com/github/MehrabHussain47/Python-Self-Practice/blob/master/Class_10.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Pandas
#### Pandas Data Manipulation Basics
#### Loading Data into Pandas (CSV, Excel)
#### Selecting and Filtering Data in Dataframe

In [204]:
import pandas as pd

In [205]:
data = {  # Here it is a json data with 3 panda's characteristics
    'Name': ['Pandy', 'Bamboo', 'Fuzzy'],
    'Age': [5, 7, 4],
    'Bamboo_Sticks': [15, 20, 12]  # dictionary is a form of json (file type)
}

In [206]:
df = pd.DataFrame(data)
print(df)

     Name  Age  Bamboo_Sticks
0   Pandy    5             15
1  Bamboo    7             20
2   Fuzzy    4             12

In [207]:
df['Age'] < 6 # Will show the logic

0     True
1    False
2     True
Name: Age, dtype: bool

In [208]:
temp_data = df[df['Age'] < 6] # Filter if Age is less than 6

In [209]:
print(temp_data)

    Name  Age  Bamboo_Sticks
0  Pandy    5             15
2  Fuzzy    4             12

In [210]:
df['Job'] = ['Intern', 'Mananger', 'Intern']  # Adding one column in dataframe

In [211]:
print(df)

     Name  Age  Bamboo_Sticks       Job
0   Pandy    5             15    Intern
1  Bamboo    7             20  Mananger
2   Fuzzy    4             12    Intern

In [212]:
df = df.drop('Bamboo_Sticks', axis=1) # Deleting one column in dataframe
# axis = 0 means row and axis = 1 means colomn

In [213]:
print(df)

     Name  Age       Job
0   Pandy    5    Intern
1  Bamboo    7  Mananger
2   Fuzzy    4    Intern

In [215]:
df = df[df['Name'] != 'Fuzzy']
# df = df.set_index('Name')
# df = df.drop('Fuzzy', axis=0) # Deleting one row in dataframe

In [216]:
print(df)

     Name  Age       Job
0   Pandy    5    Intern
1  Bamboo    7  Mananger

In [217]:
# loc = lebelled index er location track korar jonno
# iloc = index er location track korar jonno

In [218]:
data = {
    'Name': ['Pandy', 'Bamboo', 'Fuzzy'],
    'Age': [5, 7, 4],
    'Bamboo_Sticks': [15, 20, 12],
}
# index 0, 1, 2 nah kore a, b, c dile => lebelled index

In [219]:
df = pd.DataFrame(data, index=['a', 'b', 'c'])
print(df)

     Name  Age  Bamboo_Sticks
a   Pandy    5             15
b  Bamboo    7             20
c   Fuzzy    4             12

In [220]:
df.loc['c'] # c er under e show row chole ashbe

Name             Fuzzy
Age                  4
Bamboo_Sticks       12
Name: c, dtype: object

In [221]:
df.loc[['a', 'c'], ['Name', 'Age']] # c and a er under e specific row (Name, Age) chole ashbe

    Name  Age
a  Pandy    5
c  Fuzzy    4

In [222]:
data = {
    'Name': ['Pandy', 'Bamboo', 'Fuzzy'],
    'Age': [5, 7, 4],
    'Bamboo_Sticks': [15, 20, 12],
}
df = pd.DataFrame(data)
print(df)

     Name  Age  Bamboo_Sticks
0   Pandy    5             15
1  Bamboo    7             20
2   Fuzzy    4             12

In [223]:
print(df.iloc[2]) # index er under e row ashbe

Name             Fuzzy
Age                  4
Bamboo_Sticks       12
Name: 2, dtype: object

In [224]:
print(df['Age'].iloc[2])  # index er under e specific row ashbe

4

In [167]:
from google.colab import files
uploaded = files.upload()

Saving test.json to test (10).json

In [168]:
df = pd.read_json('test.json')

In [169]:
print(df)

   Duration  Pulse  Maxpulse  Calories
0        60    110       130       409
1        60    117       145       479
2        60    103       135       340
3        45    109       175       282
4        45    117       148       406
5        60    102       127       300

In [170]:
df.head()

   Duration  Pulse  Maxpulse  Calories
0        60    110       130       409
1        60    117       145       479
2        60    103       135       340
3        45    109       175       282
4        45    117       148       406

In [171]:
df.to_csv('Output.csv', index=False) # index = False nah dile csv file e index column add hobe
# new csv file create hoye save hobe jeta 'Output.csv'

In [172]:
df.to_excel('Output.xlsx', index=False)
# new excel file create hoye save hobe jeta 'Output.xlsx'

In [173]:
df.to_json('Output.json', orient='records', lines=True) # lines=True dile ek line er vitor shob records dekhabe
# but ekhane per row different lines er vitor records dekhabe
# new json file create hoye save hobe jeta 'Output.json'

In [144]:
df = df[['Duration', 'Pulse']]

In [145]:
print(df)

   Duration  Pulse
0        60    110
1        60    117
2        60    103
3        45    109
4        45    117
5        60    102

In [156]:
df = df[~(df['Duration'] > 50)]

In [157]:
print(df)

   Duration  Pulse  Maxpulse  Calories
3        45    109       175       282
4        45    117       148       406

In [165]:
df = df[(df['Duration'] > 50) & (df['Pulse'] > 105)]

In [166]:
print(df)

   Duration  Pulse  Maxpulse  Calories
0        60    110       130       409
1        60    117       145       479

In [174]:
df = df[(df['Duration'] > 50) | (df['Pulse'] > 105)]

In [175]:
print(df)

   Duration  Pulse  Maxpulse  Calories
0        60    110       130       409
1        60    117       145       479
2        60    103       135       340
3        45    109       175       282
4        45    117       148       406
5        60    102       127       300

In [176]:
df.to_excel('Output.xlsx', index=False)

In [178]:
# Think: SQL-style joins. Match rows based on common columns.
# merging two json files
left = pd.DataFrame({
    'ID': [1, 2, 3],
    'Name': ['Pandy', 'Fuzzy', 'Bamboo']
})

right = pd.DataFrame({
    'ID': [1, 2, 4],
    'Hobby': ['Climbing', 'Sleeping', 'Eating']
})

In [179]:
print(left)

   ID    Name
0   1   Pandy
1   2   Fuzzy
2   3  Bamboo

In [180]:
print(right)

   ID     Hobby
0   1  Climbing
1   2  Sleeping
2   4    Eating

In [181]:
# Merge on common column ID
merged = pd.merge(left, right, on='ID', how='inner')
print(merged)

   ID   Name     Hobby
0   1  Pandy  Climbing
1   2  Fuzzy  Sleeping

In [182]:
merged = pd.merge(left, right, on='ID', how='left')
print(merged)

   ID    Name     Hobby
0   1   Pandy  Climbing
1   2   Fuzzy  Sleeping
2   3  Bamboo       NaN

In [183]:
merged = pd.merge(left, right, on='ID', how='right')
print(merged)

   ID   Name     Hobby
0   1  Pandy  Climbing
1   2  Fuzzy  Sleeping
2   4    NaN    Eating

In [185]:
# using join operation
left = pd.DataFrame({
    'ID': [1, 2, 3],
    'Name': ['Pandy', 'Fuzzy', 'Bamboo']
}).set_index('ID')

right = pd.DataFrame({
    'ID': [1, 2, 4],
    'Hobby': ['Climbing', 'Sleeping', 'Eating']
}).set_index('ID')
join_data = left.join(right, how = 'inner')
print(join_data)

     Name     Hobby
ID
1   Pandy  Climbing
2   Fuzzy  Sleeping

In [186]:
# Think: SQL-style joins. Match rows based on common columns.
# concatenate two json files in row wised
left = pd.DataFrame({
    'ID': [1, 2, 3],
    'Name': ['Pandy', 'Fuzzy', 'Bamboo']
})

right = pd.DataFrame({
    'ID': [1, 2, 4],
    'Name': ['Climbing', 'Sleeping', 'Eating']
})
# column name duita same thakte hobe

In [187]:
print(left)

   ID    Name
0   1   Pandy
1   2   Fuzzy
2   3  Bamboo

In [188]:
print(right)

   ID      Name
0   1  Climbing
1   2  Sleeping
2   4    Eating

In [189]:
concat_data = pd.concat([left, right], axis=0)
print(concat_data)

   ID      Name
0   1     Pandy
1   2     Fuzzy
2   3    Bamboo
0   1  Climbing
1   2  Sleeping
2   4    Eating

In [190]:
# Think: SQL-style joins. Match rows based on common columns.
# concatenate two json files in column wised
left = pd.DataFrame({
    'ID': [1, 2, 3],
    'Name': ['Pandy', 'Fuzzy', 'Bamboo']
})

right = pd.DataFrame({
    'ID_2': [1, 2, 4],
    'Hobby': ['Climbing', 'Sleeping', 'Eating']
})
# column name duita different thakte hobe

In [191]:
concat_data = pd.concat([left, right], axis=1)
print(concat_data)

   ID    Name  ID_2     Hobby
0   1   Pandy     1  Climbing
1   2   Fuzzy     2  Sleeping
2   3  Bamboo     4    Eating